export default {
  /* tokens */
  ['primary-container']: 'var(--md-sys-color-primary-container)',
  ['on-primary']: 'var(--md-sys-color-on-primary)',
  ['on-primary-container']: 'var(--md-sys-color-on-primary-container)',
  ['inverse-primary']: 'var(--md-sys-color-inverse-primary)',
  ['secondary-container']: 'var(--md-sys-color-secondary-container)',
  ['on-secondary']: 'var(--md-sys-color-on-secondary)',
  ['on-secondary-container']: 'var(--md-sys-color-on-secondary-container)',
  ['tertiary-container']: 'var(--md-sys-color-tertiary-container)',
  ['on-tertiary']: 'var(--md-sys-color-on-tertiary)',
  ['on-tertiary-container']: 'var(--md-sys-color-on-tertiary-container)',
  ['surface']: 'var(--md-sys-color-surface)',
  ['surface-dim']: 'var(--md-sys-color-surface-dim)',
  ['surface-bright']: 'var(--md-sys-color-surface-bright)',
  ['surface-container-lowest']: 'var(--md-sys-color-surface-container-lowest)',
  ['surface-container-low']: 'var(--md-sys-color-surface-container-low)',
  ['surface-container']: 'var(--md-sys-color-surface-container)',
  ['surface-container-high']: 'var(--md-sys-color-surface-container-high)',
  ['surface-container-highest']:
    'var(--md-sys-color-surface-container-highest)',
  ['surface-variant']: 'var(--md-sys-color-surface-variant)',
  ['on-surface']: 'var(--md-sys-color-on-surface)',
  ['on-surface-variant']: 'var(--md-sys-color-on-surface-variant)',
  ['inverse-surface']: 'var(--md-sys-color-inverse-surface)',
  ['inverse-on-surface']: 'var(--md-sys-color-inverse-on-surface)',
  ['background']: 'var(--md-sys-color-background)',
  ['on-background']: 'var(--md-sys-color-on-background)',
  ['error-container']: 'var(--md-sys-color-error-container)',
  ['on-error']: 'var(--md-sys-color-on-error)',
  ['on-error-container']: 'var(--md-sys-color-on-error-container)',
  ['outline']: 'var(--md-sys-color-outline)',
  ['outline-variant']: 'var(--md-sys-color-outline-variant)',
  ['shadow']: 'var(--md-sys-color-shadow)',
  ['surface-tint-color']: 'var(--md-sys-color-surface-tint-color)',
  ['scrim']: 'var(--md-sys-color-scrim)',
  /* primary */
  primary: {
    DEFAULT: 'var(--md-sys-color-primary)',
    0: 'var(--md-ref-palette-primary0)',
    10: 'var(--md-ref-palette-primary10)',
    20: 'var(--md-ref-palette-primary20)',
    25: 'var(--md-ref-palette-primary25)',
    30: 'var(--md-ref-palette-primary30)',
    35: 'var(--md-ref-palette-primary35)',
    40: 'var(--md-ref-palette-primary40)',
    50: 'var(--md-ref-palette-primary50)',
    60: 'var(--md-ref-palette-primary60)',
    70: 'var(--md-ref-palette-primary70)',
    80: 'var(--md-ref-palette-primary80)',
    90: 'var(--md-ref-palette-primary90)',
    95: 'var(--md-ref-palette-primary95)',
    98: 'var(--md-ref-palette-primary98)',
    99: 'var(--md-ref-palette-primary99)',
    100: 'var(--md-ref-palette-primary100)'
  },
  /* secondary */
  secondary: {
    DEFAULT: 'var(--md-sys-color-secondary)',
    0: 'var(--md-ref-palette-secondary0)',
    10: 'var(--md-ref-palette-secondary10)',
    20: 'var(--md-ref-palette-secondary20)',
    25: 'var(--md-ref-palette-secondary25)',
    30: 'var(--md-ref-palette-secondary30)',
    35: 'var(--md-ref-palette-secondary35)',
    40: 'var(--md-ref-palette-secondary40)',
    50: 'var(--md-ref-palette-secondary50)',
    60: 'var(--md-ref-palette-secondary60)',
    70: 'var(--md-ref-palette-secondary70)',
    80: 'var(--md-ref-palette-secondary80)',
    90: 'var(--md-ref-palette-secondary90)',
    95: 'var(--md-ref-palette-secondary95)',
    98: 'var(--md-ref-palette-secondary98)',
    99: 'var(--md-ref-palette-secondary99)',
    100: 'var(--md-ref-palette-secondary100)'
  },
  /* tertiary */
  tertiary: {
    DEFAULT: 'var(--md-sys-color-tertiary)',
    0: 'var(--md-ref-palette-tertiary0)',
    10: 'var(--md-ref-palette-tertiary10)',
    20: 'var(--md-ref-palette-tertiary20)',
    25: 'var(--md-ref-palette-tertiary25)',
    30: 'var(--md-ref-palette-tertiary30)',
    35: 'var(--md-ref-palette-tertiary35)',
    40: 'var(--md-ref-palette-tertiary40)',
    50: 'var(--md-ref-palette-tertiary50)',
    60: 'var(--md-ref-palette-tertiary60)',
    70: 'var(--md-ref-palette-tertiary70)',
    80: 'var(--md-ref-palette-tertiary80)',
    90: 'var(--md-ref-palette-tertiary90)',
    95: 'var(--md-ref-palette-tertiary95)',
    98: 'var(--md-ref-palette-tertiary98)',
    99: 'var(--md-ref-palette-tertiary99)',
    100: 'var(--md-ref-palette-tertiary100)'
  },
  /* neutral */
  neutral: {
    0: 'var(--md-ref-palette-neutral0)',
    10: 'var(--md-ref-palette-neutral10)',
    20: 'var(--md-ref-palette-neutral20)',
    25: 'var(--md-ref-palette-neutral25)',
    30: 'var(--md-ref-palette-neutral30)',
    35: 'var(--md-ref-palette-neutral35)',
    40: 'var(--md-ref-palette-neutral40)',
    50: 'var(--md-ref-palette-neutral50)',
    60: 'var(--md-ref-palette-neutral60)',
    70: 'var(--md-ref-palette-neutral70)',
    80: 'var(--md-ref-palette-neutral80)',
    90: 'var(--md-ref-palette-neutral90)',
    95: 'var(--md-ref-palette-neutral95)',
    98: 'var(--md-ref-palette-neutral98)',
    99: 'var(--md-ref-palette-neutral99)',
    100: 'var(--md-ref-palette-neutral100)'
  },
  /* neutral-variant */
  ['neutral-variant']: {
    0: 'var(--md-ref-palette-neutral-variant0)',
    10: 'var(--md-ref-palette-neutral-variant10)',
    20: 'var(--md-ref-palette-neutral-variant20)',
    25: 'var(--md-ref-palette-neutral-variant25)',
    30: 'var(--md-ref-palette-neutral-variant30)',
    35: 'var(--md-ref-palette-neutral-variant35)',
    40: 'var(--md-ref-palette-neutral-variant40)',
    50: 'var(--md-ref-palette-neutral-variant50)',
    60: 'var(--md-ref-palette-neutral-variant60)',
    70: 'var(--md-ref-palette-neutral-variant70)',
    80: 'var(--md-ref-palette-neutral-variant80)',
    90: 'var(--md-ref-palette-neutral-variant90)',
    95: 'var(--md-ref-palette-neutral-variant95)',
    98: 'var(--md-ref-palette-neutral-variant98)',
    99: 'var(--md-ref-palette-neutral-variant99)',
    100: 'var(--md-ref-palette-neutral-variant100)'
  },
  /* error */
  error: {
    DEFAULT: 'var(--md-sys-color-error)',
    0: 'var(--md-ref-palette-error0)',
    10: 'var(--md-ref-palette-error10)',
    20: 'var(--md-ref-palette-error20)',
    25: 'var(--md-ref-palette-error25)',
    30: 'var(--md-ref-palette-error30)',
    35: 'var(--md-ref-palette-error35)',
    40: 'var(--md-ref-palette-error40)',
    50: 'var(--md-ref-palette-error50)',
    60: 'var(--md-ref-palette-error60)',
    70: 'var(--md-ref-palette-error70)',
    80: 'var(--md-ref-palette-error80)',
    90: 'var(--md-ref-palette-error90)',
    95: 'var(--md-ref-palette-error95)',
    98: 'var(--md-ref-palette-error98)',
    99: 'var(--md-ref-palette-error99)',
    100: 'var(--md-ref-palette-error100)'
  }
};
